version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV:-dev}
      - JVM_OPTS=${JVM_OPTS:-"-Xmx512m -Xms256m"}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-fake_db}
      - MYSQL_USER=${MYSQL_USER:-fake_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-fake_password}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-fake_db}
      - MYSQL_USER=${MYSQL_USER:-fake_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-fake_password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-fake_password}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:  # 添加健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge


