version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV:-dev}
      - JVM_OPTS=${JVM_OPTS:-"-Xmx512m -Xms256m"}
    depends_on:
      - mysql
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-testdb}
      - MYSQL_USER=${MYSQL_USER:-appuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge
