spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:fake_db}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:fake_user}
    password: ${MYSQL_PASSWORD:fake_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://dev.api.todocalendar.live/api/oauth2/callback/google"
            scope:
              - email
              - profile

server:
  forward-headers-strategy: NATIVE
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
    org.springframework.jdbc: DEBUG
    # Add MyBatis mapper logging
    com.example.mapper: DEBUG
    org.mybatis: DEBUG 