spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:fake_db}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:fake_user}
    password: ${MYSQL_PASSWORD:fake_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql

logging:
  level:
    root: ERROR
    org.springframework.web: WARN
    com.example: INFO 