spring:
  application:
    name: todo-calendar
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080 

jwt:
  secret: ${JWT_SECRET:your_default_jwt_secret_key_here}
  expiration: 86400000  # 24 hours in milliseconds 

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG 