spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todocalendar_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: appuser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
    org.springframework.jdbc: DEBUG 