DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS calendar;

CREATE TABLE users (
    id INT IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE calendar (
    id INT IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    checked BOOLEAN NOT NULL,
    important BOOLEAN NOT NULL,
    createTime DATETIME NOT NULL,
    expireTime DATETIME,
    updateTime DATETIME NOT NULL,
    createDate DATE NOT NULL,
    userId INT NOT NULL
);

